version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qrdomotik
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL:-file:./db/custom.db}
    volumes:
      - qrdomotik-db:/app/db
    restart: unless-stopped

volumes:
  qrdomotik-db:
